### ISSUE TITLE
setLocale is not switching the mat-datepicker localization 

### ISSUE THREAD

**Issue by ivayloc** [sapozhnikovay/ngx-mat-datefns-date-adapter#3]
I have installed the adapter (v9.0.2) but when I am changing the localization of the app through Materrial `DateAdapter` `setLocale()` method the localization for the Angular Material Datepicker, is not changing. I am using it with Angular 8 is it possible to work?

**Comment by sapozhnikovay** [comment]
Hello, Ivaylo. I've not tried version 9 of ngx-mat-datefns-date-adapter with Angular 8 yet. Could you please create a small reproduction? You can use stackblitz.com or similar service.
Also what kind of ChangeDetectionStrategy do you use in target component? Maybe mat-datepicker component is somehow isolated from locale change propagation?
And what are the source and target locales? I'll look if there are any issues with them on the dateFns side.

**Comment by sapozhnikovay** [comment]
I've extended the Angular 9 stackblitz example with the buttons and the method to change locale. Perhaps it will help you to determine the root cause:

https://stackblitz.com/edit/angular-ngx-mat-datefns-date-adapter-9-locale-change?file=src/app/app.component.ts

Datepicker in A8 and A9 has the same interface for locale management:
https://v8.material.angular.io/components/datepicker/overview#setting-the-locale-code
